version: '3'

services:
  app:
    networks:
      br-network:
        ipv4_address: 172.20.0.10
    build: '.'
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
      - /tmp/:/var/lib/sqlite/

  elastic:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.4.2
    networks:
      br-network:
        ipv4_address: 172.20.0.11
    depends_on:
      - app
    ports:
      - 9200:9200
    environment:
      - node.name=es01
      - cluster.name=es-docker-cluster
      - discovery.type=single-node

  kibana:
    image: docker.elastic.co/kibana/kibana:7.4.2
    networks:
      br-network:
        ipv4_address: 172.20.0.12
    depends_on:
      - app
    ports:
      - 5601:5601
    environment:
      ELASTICSEARCH_URL: http://172.20.0.11:9200
      ELASTICSEARCH_HOSTS: http://172.20.0.11:9200

networks:
  br-network:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 172.20.0.0/16